### ISSUE TITLE
 Kanban board review

### ISSUE THREAD

**Issue by Abdelaziz-Mahdi** [kambereBr/Recipe-App#12]
https://github.com/kambereBr/Recipe-App/projects/1
We are a team of 3 people.

**Comment by MahmoudBakr23** [comment]
Hi @Abdelaziz-Mahdi, @kambereB, and @ahmed025566😃, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

**Highlights**
- Well done on dividing the tasks between the team members equally
- Good job covering all of the required tasks for a 3-member team
- Descriptive summary

Cheers, and Happy coding!👏👏👏

Feel free to mention @MahmoudBakr23 to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
